#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to respect above requirements.
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
