#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to respect above requirements.
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i 's/location \/ {/location \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;/' /etc/nginx/sites-available/default
sudo service nginx start
