#!/usr/bin/env bash
# Install your load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend app
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 3331-web-01 18.207.125.211:80 check
    server 3331-web-02 	3.91.17.213:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
