#!/usr/bin/env bash
#change server's local host and facebook.com
cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2/' ~/hosts.new
sed -i '2i8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
rm -f ~/hosts.new
